Reduces corpus payload changes
Hypertopic/Argos pull request #57
Opened 2020-04-05 19:13 UTC by garnier5

2020-04-06 13:16 UTC, benel requested changes
- [ ] Pour le code, voir les commentaires ligne par ligne,
- [ ] Pour le titre du commit, merci d'appliquer les [règles de nommage](https://github.com/Hypertopic/Porphyry/blob/v7/.github/pull_request_template.md).

Merci d'avance.

2020-04-06 13:16 UTC, benel commented on app/views/corpus/map.js
> +      case "_rev":
Attention à ne pas introduire des modifications sans liens avec votre contribution.
Pour éviter cela, utilisez l'ajout ligne à ligne par exemple de l'interface d'Atom pour préparer les commits.

2020-04-06 13:16 UTC, benel commented on app/views/corpus/map.js
> +    emit([o._id], entry);
Vous pouvez simplifier tout ça... Si vous avez un tableau et que vous avez besoin d'un tableau, pourquoi en refabriquer un ?

2020-04-06 13:16 UTC, benel commented on app/views/corpus/map.js
> +      };
J'ai l'impression que vous ne faites pas un tableau mais qu'au contraire chaque catégorie vient écraser la précédente. Avez-vous lancé les tests pour vérifier qu'ils fonctionnaient toujours ?

2020-04-06 13:38 UTC, benel commented
En plus des tests automatisés dans Porphyry à lancer à la main, il faudra aussi penser à modifier en conséquence les [tests d'Argos pour la version 2 d'Hypertopic](https://github.com/Hypertopic/Argos/blob/v4/__tests__/api/hypertopic_v2.js).

2020-04-10 13:50 UTC, garnier5 commented on app/views/corpus/map.js
> +      };
Lorsqu'on les regroupe dans un tableau, les badges accompagnant les topics dans Porphyry disparaissent. Faut-il modifier le code de Porphyry pour prendre en compte la nouvelle syntaxe ?

2020-04-10 14:10 UTC, benel commented on app/views/corpus/map.js
> +      };
Non, non, c'est la nouvelle structure qui ne doit pas être correcte...

2020-04-10 14:14 UTC, benel commented on app/views/corpus/map.js
> +      };
L'idée est de changer le format mais d'avoir strictement le même résultat après parsing par la bibliothèque.

2020-04-10 14:20 UTC, benel commented on app/views/corpus/map.js
> +      };
Vous pouvez au choix : 
- comparer à l'œil les deux formats pour voir ce qui ne va pas,
- regarder le résultat du parsing des deux par Hypertopic/lib-node,
- réécrire les tests pour qu'ils s'appuient sur Hypertopic/lib-node.

2020-04-10 14:27 UTC, benel commented
Voici un bout de code Node.js pour tester le parsing (vous pouvez le faire [ici](https://npm.runkit.com/hypertopic)) : 

```node
var hypertopic = require("hypertopic");

let db = hypertopic([
  "http://argos2.test.hypertopic.org"
]);

const _log = (x) => console.log(JSON.stringify(x, null, 2));
const _error = (x) => console.error(x.message);

db.getView('/item/Vitraux - Bénel/85bb03f5e4930f3b9d1ef9afbfa92421b8e2e23b')
  .then(_log);
```

Et voici le résultat:
```json
{
  "Vitraux - Bénel": {
    "85bb03f5e4930f3b9d1ef9afbfa92421b8e2e23b": {
      "topic": [
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "8e2a5c829fee6845bb5c4b3e4cc482b4"
        },
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "55cc1d454d3dd877b8940854a673e858"
        },
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "49c47e68f7bb134ebe62769563d5c590"
        },
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "3e02bce4cf58ed419a31b4e585d7f1f1"
        },
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "26c335f158caf74881c1e802680f8be5"
        },
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "a2febe0107e45f49bed820cbb43f468d"
        },
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "c5050690f690514986e189ccaa9fa3ec"
        },
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "ff69b3487ba60d4d8e2ea00441bba238"
        },
        {
          "viewpoint": "a76306e4f17ed4f79e7e481eb9a1bd06",
          "id": "535f6027ddaa7e4f9de38a5d2e4eecdb"
        },
        {
          "viewpoint": "a76306e4f17ed4f79e7e481eb9a1bd06",
          "id": "a091a7083b09aa4e86a7fa384b542ad3"
        },
        {
          "viewpoint": "a76306e4f17ed4f79e7e481eb9a1bd06",
          "id": "d2ed0017689f7d4081890c4ce6d99934"
        }
      ],
      "spatial": [
        "Église Saint-Nizier, Troyes"
      ],
      "resource": [
        "http://steatite.hypertopic.org/picture/85bb03f5e4930f3b9d1ef9afbfa92421b8e2e23b"
      ],
      "creator": [
        "Aurélien Bénel"
      ]
    }
  }
}
```

2020-04-10 14:28 UTC, benel commented
L'idée est que vous ayez le même résultat après le refactoring.

2020-04-10 15:17 UTC, garnier5 commented on app/views/corpus/map.js
> +      };
- A l'oeil, mon tableau topic ressemble beaucoup à celui donné en exemple.
- On dirait que ce n'est pas possible de lancer npm runkit avec mon argos local, il me renvoit un résultat vide à chaque fois.

2020-04-10 15:40 UTC, benel commented
> On dirait que ce n'est pas possible de lancer npm runkit avec mon argos local, il me renvoit un résultat vide à chaque fois.

C'est possible... Essayez quand même au cas où d'ajouter "https://npm.runkit.com" dans les domaines autorisés dans la [configuration CORS de votre CouchDB](http://localhost:5984/_utils/#_config/nonode@nohost/cors).

2020-04-10 15:46 UTC, garnier5 commented
> C'est possible... Essayez quand même au cas où d'ajouter `https://npm.runkit.com` dans les domaines autorisés dans la [configuration CORS de votre CouchDB](http://localhost:5984/_utils/#_config/nonode@nohost/cors).

Aucun changement, il me renvoit toujours un json complètement vide.

2020-04-11 09:50 UTC, garnier5 commented
J'ai trouvé pourquoi il est impossible de rassembler les topics en un tableau. 
La librairie "lib-node" pose problème [ici](https://github.com/Hypertopic/lib-node/blob/master/src/index.js#L69), car elle ne vérifie pas si ce qui est renvoyé est un tableau.

La version actuelle : 
`
"topic": [
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "26c335f158caf74881c1e802680f8be5"
        },
        {
          "viewpoint": "56e092d8a6179a788c74b618b29801c0",
          "id": "49c47e68f7bb134ebe62769563d5c590"
        },
        ...
      ],
`

Ma version locale : 
`
"topic": [
	 //Fusionner le tableau dans le tableau
        [
          {
            "viewpoint": "56e092d8a6179a788c74b618b29801c0",
            "id": "26c335f158caf74881c1e802680f8be5"
          },
          {
            "viewpoint": "56e092d8a6179a788c74b618b29801c0",
            "id": "8e2a5c829fee6845bb5c4b3e4cc482b4"
          },
         ...
        ]
      ],
`

Je ne pense pas qu'il soit possible d'améliorer l'envoi des topics sans revoir la librairie.
Qu'en pensez-vous ?

2020-04-14 13:35 UTC, benel commented
> J'ai trouvé pourquoi il est impossible de rassembler les topics en un tableau.
La librairie "lib-node" pose problème ici, car elle ne vérifie pas si ce qui est renvoyé est un tableau.

Je suis en train de créer des tests unitaires pour mieux comprendre le problème (branche dev de la bibliothèque disponible d'ici quelques minutes)... N'hésitez pas à me suggérer des tests supplémentaires pour illustrer le problème.

2020-04-14 14:00 UTC, garnier5 commented
Est-ce qu'on est sur qu'avec ce [test](https://github.com/Hypertopic/lib-node/blob/dev/__tests__/parsing.js#L23), on a le même résultat que celui-là : 

```
it('assigns an object to another one by concatenating values into arrays', () =>  {
  let o1 = {
    b: ["c"]
  };
  _assign(o1, {
    b: ["d"],
    e: "f"
  });
  expect(o1).toEqual({
    b: ["c", "d"],
    e: ["f"]
  });
});
```

Parce que c'est justement notre problème dans la résolution de ce ticket.

Aussi, comment peut-on lancer ces tests ?
Est-ce qu'il faut "forker" la bibliothèque puis la cloner comme nous le faisons avec Argos ?

2020-04-14 14:07 UTC, benel commented
> Est-ce qu'on est sur qu'avec ce test, on a le même résultat que celui-là 

Pour l'instant, j'ai juste automatisé les tests qui étaient en commentaires.
Je vais regarder le test que vous proposez. S'il échoue effectivement on pourra l'ajouter et essayer de le résoudre.

> Est-ce qu'il faut "forker" la bibliothèque puis la cloner comme nous le faisons avec Argos ?

Oui, oui, tout à fait.

2020-04-14 15:32 UTC, benel commented
Voilà : le [fix](https://github.com/Hypertopic/lib-node/commit/a2aec0199869c397b72b7a8f555e70f2b119229b) a été publié dans la bibliothèque Hypertopic/lib-node et Porphyry a été mis à jour pour l'intégrer.

Vous pouvez vous servir de la bibliothèque pour simplifier et rendre plus robustes les tests d'Argos.

2020-04-16 07:52 UTC, benel commented
@garnier5 Ça vous aiderait si je m'occupais du refactoring des tests ?

2020-04-16 08:18 UTC, garnier5 commented
@benel j'ai commencé un peu, mais je ne peux pas vous garantir de réussir rapidement 
Si vous jugez que les tests s’éloignent du sujet initial, je peux effectivement vous laissez travailler sur leur refactoring

2020-04-16 10:00 UTC, garnier5 commented
J'ai réalisé les modifications dont nous avions parlé la semaine dernière. Elles sont normalement disponibles dans ce `pull request`.

2020-04-16 20:16 UTC, benel commented
@garnier5 J'ai mis à jour les tests : 

1. Ils sont plus permissifs sur les données (ils fonctionnent sur le mini-corpus de tests, sur le serveur de production et le serveur de test),
2. Ils sont plus permissifs sur la structure (comme ils s'appuient sur la bibliothèque Hypertopic/lib-node ils devraient fonctionner avec votre refactoring).

Je vous laisse faire un cherry-pick de votre commit au-dessus des miens (si vous avez besoin d'aide avec git, demandez moi). Vous pourrez voir ainsi si votre code passe les tests.

2020-04-18 08:17 UTC, garnier5 commented
J'ai un problème au niveau des tests.
La fonction "toBeDefined" n'a pas l'air d'être défini lorsque je lance mes tests.
Est-ce une fonction d'une autre librairie dont je n'ai pas connaissance ?

2020-04-18 08:21 UTC, benel commented
> La fonction "toBeDefined" n'a pas l'air d'être défini lorsque je lance mes tests.
Est-ce une fonction d'une autre librairie dont je n'ai pas connaissance ?

C'est une [méthode de Jest](https://jestjs.io/docs/en/expect#tobedefined).

2020-04-18 08:38 UTC, garnier5 commented
J'ai des erreurs à propos des noms d'items et de corpus, notamment sur les tests : 
`Get a corpus to get contained items and highlights with their attributes and topics`
`Get an item to get its highlights, attributes and topics`
Est-ce que je dois faire un `docker-compose up test-data` dans ma base de données locale ?

2020-04-18 09:05 UTC, benel commented
> Est-ce que je dois faire un docker-compose up test-data dans ma base de données locale ?

Si n'avez pas changé l'[URI indiquée dans les tests](https://github.com/Hypertopic/Argos/blob/v4/__tests__/api/hypertopic_v2.js#L5). Oui, c'est testé sur la base locale que vous devez effectivement initialiser avec `docker-compose up test-data` (voire juste `docker-compose up`qui va exécuter tous les services dont l'envoi des données de test).

2020-04-18 09:14 UTC, garnier5 commented
Le problème, c'est qu'il ne récupère aucune donnée lorsque j'utilise l'URI `localhost`.

2020-04-18 09:17 UTC, benel commented
Vérifiez si les données ont été importées en ouvrant http://localhost/ dans un navigateur.

2020-04-18 09:19 UTC, benel commented
```
% docker-compose up -d
Starting argos_couchdb_1 ... done
Starting argos_test_data_1 ... done
Starting argos_proxy_1     ... done
Starting argos_argos_1     ... done
```

2020-04-18 09:20 UTC, garnier5 commented
> 
> 
> Vérifiez si les données ont été importées en ouvrant http://localhost/ dans un navigateur.

Je n'ai aucune donnée lorsque j'ouvre localhost.
Est-ce que le fait d'utiliser Windows Famille n'empêche pas l'utilisation de localhost ?

2020-04-18 09:22 UTC, garnier5 commented
```
$ docker-compose up test_data
argos_couchdb_1 is up-to-date
Creating argos_test_data_1 ... done                                                                                     
Attaching to argos_test_data_1
argos_test_data_1 exited with code 0

$ docker-compose up -d
argos_couchdb_1 is up-to-date
argos_proxy_1 is up-to-date
Starting argos_test_data_1 ... done                                                                                     
Starting argos_argos_1     ... done  
```

2020-04-18 09:23 UTC, benel commented
> Est-ce que le fait d'utiliser Windows Famille n'empêche pas l'utilisation de localhost ?

Effectivement, avec Docker Toolbox, vous êtes dans ce cas là :
https://github.com/orgs/Hypertopic/teams/connexion-a-un-service-en-conteneur

2020-04-18 09:25 UTC, benel commented
Donc testez http://192.168.99.100/ pour voir si vous les avez les données. Et modifiez en conséquence l'URI dans le fichier de test.

2020-04-18 09:25 UTC, benel commented
Vous devriez voir quelque chose de ce genre : 
<img width="616" alt="Capture d’écran 2020-04-18 à 11 20 27" src="https://user-images.githubusercontent.com/597307/79633841-58398280-8167-11ea-9ff6-6ffda463ed52.png">

2020-04-18 09:28 UTC, benel commented
> argos_test_data_1 exited with code 0

Ça par contre c'est curieux. Parce que normalement c'est à docker-compose de gérer son serveur virtuel.

Recommencez proprement : 

```
docker-compose down
docker-compose up -d
```

2020-04-18 09:34 UTC, garnier5 commented
> Recommencez proprement :

Curieusement, j'ai maintenant différentes couleurs de police (vert, rouge...). 
Mais j'utilisais déjà cette URI depuis le début. Et le `docker-compose` n'a malheureusement pas réglé le problème de nom pour le test `Get a corpus to get contained items and highlights with their attributes and topics`.

2020-04-18 09:36 UTC, benel commented
> Mais j'utilisais déjà cette URI depuis le début.

Dans le test manuel (dans le navigateur) ? Ou bien dans les tests automatisés ?

2020-04-18 09:37 UTC, benel commented
> le problème de nom pour le test Get a corpus to get contained items and highlights with their attributes and topics.

Peut-être que le test fonctionne et qu'il y a réellement un problème dans la structure que vous envoyez...

Les autres tests fonctionnent ?

2020-04-18 09:43 UTC, garnier5 commented
> Dans le test manuel (dans le navigateur) ? Ou bien dans les tests automatisés ?

Les deux. 

>Peut-être que le test fonctionne et qu'il y a réellement un problème dans la structure que vous envoyez...
>Les autres tests fonctionnent ?

Les autres tests de la v2 fonctionne.
Est-ce que le [test](https://github.com/Hypertopic/Argos/blob/v4/__tests__/api/hypertopic_v2.js#L41) ne devrait pas appeler `corpus_name` comme dans les [données](https://github.com/Hypertopic/Argos/blob/v4/__tests__/api/fixtures/vitraux.json#L3)?

2020-04-18 09:44 UTC, benel commented
Les tests d'intégration continue eux ont réussi (voir ci-dessous en cliquant sur "All checks jhave passed" et ensuite sur "Details").
Donc je suspecterai plutôt un problème avec votre environnement de test local.

2020-04-18 09:45 UTC, benel commented
> Est-ce que le test ne devrait pas appeler corpus_name comme dans les données?

Non. D'ailleurs si vous regardez dans [votre code](https://github.com/Hypertopic/Argos/pull/57/files#diff-cba3fb258f8c6f15d4b50653286e04f2R23), vous avez bien renommé `corpus_name` en `name`.

2020-04-18 09:47 UTC, benel commented
Pourriez-vous donner le message du test d'erreur complet (ça fait entre 3 et 5 lignes) ?

2020-04-18 09:49 UTC, garnier5 commented
`[{"message":"\"002bde29c23355b776f76695240588bdaef97b21.name\" must contain at least 1 items","path":["002bde29c23355b776f76695240588bdaef97b21","name"],"type":"array.min","context":{"limit":1,"value":[],"label":"002bde29c23355b776f76695240588bdaef97b21.name","key":"name"}}]`

2020-04-18 09:51 UTC, benel commented
Avez-vous les mêmes chiffres que moi dans la mire d'Argos ?

2020-04-18 09:53 UTC, garnier5 commented
> 
> 
> Avez-vous les mêmes chiffres que moi dans la mire d'Argos ?

De quels chiffres parlez-vous ?

Le test prévoit de recevoir un tableau pour le nom alors que je ne lui renvoie qu'une chaîne de caractère. Je pense que le problème vient de là...

2020-04-18 09:54 UTC, benel commented
> Le test prévoit de recevoir un tableau pour le nom alors que je ne lui renvoie qu'une chaîne de caractère. Je pense que le problème vient de là...

Non. C'est la bibliothèque qui crée les tableaux.

> De quels chiffres parlez-vous ?
<img width="616" alt="Capture d’écran 2020-04-18 à 11 20 27" src="https://user-images.githubusercontent.com/597307/79634557-62f61680-816b-11ea-8c31-5a536977e277.png">

2020-04-18 09:57 UTC, garnier5 commented
> 
> 
> > Le test prévoit de recevoir un tableau pour le nom alors que je ne lui renvoie qu'une chaîne de caractère. Je pense que le problème vient de là...
> 
> Non. C'est la bibliothèque qui crée les tableaux.
> 
> > De quels chiffres parlez-vous ?
> 
> <img alt="Capture d’écran 2020-04-18 à 11 20 27" width="616" src="https://user-images.githubusercontent.com/597307/79634557-62f61680-816b-11ea-8c31-5a536977e277.png">

Non, j'ai beaucoup plus de données que vous.
![image](https://user-images.githubusercontent.com/50024449/79634610-c3855380-816b-11ea-948d-50f99e39a07c.png)

2020-04-18 09:58 UTC, benel commented
> Non, j'ai beaucoup plus de données que vous.
C'est vrai que vous faites des tests avec des données réelles...

1. Éteignez les services docker-compose.
2. Déplacez le dossier data à un autre endroit (vous le remettrez plus tard).
3. Relancez les services de docker-compose.

2020-04-18 10:18 UTC, garnier5 commented
Vous aviez raison. Les tests passent !
Par contre, j'ai perdu quelques uns de mes `topics `dans mes données "classiques".

Voilà les `topics `restants dans le points de vue `Histoire de l'art`
```
{"id":"a76306e4f17ed4f79e7e481eb9a1bd06","key":["a76306e4f17ed4f79e7e481eb9a1bd06"],"value":{"upper":{"id":"731a7cea93dcc74abfd0a51f8201f78d","name":"Datation"}}},

{"id":"a76306e4f17ed4f79e7e481eb9a1bd06","key":["a76306e4f17ed4f79e7e481eb9a1bd06"],"value":{"upper":{"id":"6003c1197c4a1542a28e90d57b8dc5a9","name":"Technique narrative"}}},

{"id":"a76306e4f17ed4f79e7e481eb9a1bd06","key":["a76306e4f17ed4f79e7e481eb9a1bd06"],"value":{"upper":{"id":"4dbf2acc119ff3458a53ae9de59a44a7","name":"Artiste"}}},
```

Est-ce que je re-télécharge toutes les données ?

2020-04-18 10:24 UTC, benel commented
> Vous aviez raison. Les tests passent !

Bon, on est rassurés :)

> Est-ce que je re-télécharge toutes les données ?

Vous pouvez récupérer vos données à tout moment en remplaçant le dossier `data`.

Par contre ce serait bien de comprendre ce qui posait problèmes dans vos données. C'est d'autant plus curieux que les tests sont censés passer (avec l'ancien code) sur les données de production.

Vous devriez comparer les premières lignes de la vue corpus : 
- avec les données de test et avec les données réelles,
- avec le code de production et avec votre code.

2020-04-18 10:28 UTC, benel commented
# Code en production, données de test

    GET http://localhost/corpus/Vitraux%20-%20Bénel

```json
{"total_rows":22,"offset":0,"rows":[
{"id":"Vitraux - Bénel","key":["Vitraux - Bénel"],"value":{"user":"vitraux"}},
{"id":"Vitraux - Bénel","key":["Vitraux - Bénel"],"value":{"user":"aaf"}},
{"id":"Vitraux - Bénel","key":["Vitraux - Bénel"],"value":{"name":"Vitraux - Bénel"}},
...
```

# Code en production, données réelles

    GET http://argos2.hypertopic.org/corpus/Vitraux%20-%20Bénel

```json
{"total_rows":130421,"offset":121509,"rows":[
{"id":"Vitraux - Bénel","key":["Vitraux - Bénel"],"value":{"name":"Vitraux - Bénel"}},
{"id":"Vitraux - Bénel","key":["Vitraux - Bénel"],"value":{"user":"aaf"}},
{"id":"Vitraux - Bénel","key":["Vitraux - Bénel"],"value":{"user":"vitraux"}},
...
```

2020-04-18 10:34 UTC, benel commented
Ah, je viens de m'en souvenir. Si vous voulez le faire sur les données réelles vous devez mettre steatite comme deuxième serveur.

2020-04-18 10:34 UTC, benel commented
Exemple : 
```js
const db = new Hypertopic([
  'http://argos2.hypertopic.org',
  'http://steatite.hypertopic.org'
]);
```

2020-04-18 11:21 UTC, garnier5 commented
>Vous pouvez récupérer vos données à tout moment en remplaçant le dossier data (par celui que vous aviez mis de côté tout à l'heure).

Justement, mes anciennes données ont été modifié et j'ai perdu quelques `topics` pendant la manipulation.

![image](https://user-images.githubusercontent.com/50024449/79636373-7b6c2e00-8177-11ea-835e-17026a61a990.png)

![image](https://user-images.githubusercontent.com/50024449/79636367-70b19900-8177-11ea-8c82-d8ab8f0c6e1c.png)

2020-04-18 11:26 UTC, garnier5 commented
> Ah, je viens de m'en souvenir. Si vous voulez le faire sur les données réelles vous devez mettre steatite comme deuxième serveur.

Effectivement, ça marche avec les données réelles, mais j'ai toujours le même problème avec mes données locales.
Elles ont probablement été corrompu pendant les manipulations.

2020-04-18 11:32 UTC, benel commented
> Justement, mes anciennes données ont été modifié et j'ai perdu quelques topics pendant la manipulation.

Soit vous refaites toute la procédure d'import (à partir d'une base vide),
soit vous modifiez à la main les données du point de vue.

Dans la deuxième option : 
1.  Vous copiez les [bonnes données du point de vue](http://argos2.hypertopic.org/viewpoint/56e092d8a6179a788c74b618b29801c0). 
2. Vous ouvrez [votre point de vue dans CouchDB](http://localhost:5984/_utils/#database/argos/56e092d8a6179a788c74b618b29801c0), vous **gardez** l'identifiant et surtout **la révision** et vous collez les données copiées plus haut (sans l'identifiant et la révision).

2020-04-18 11:36 UTC, benel commented
Ce point de vue est le changement de données le plus évident... Si vous êtes embêté dans les tests de Porphyry avec d'autres données, c'est qu'il faut faire pareil avec [les 4 autres éléments de tests](https://github.com/Hypertopic/Argos/tree/v4/__tests__/api/fixtures) (ou au choix repartir d'une base vide et lancer la réplication).

2020-04-18 11:40 UTC, garnier5 commented
Entendu. Je vais me contenter de la deuxième option pour l'instant, en gardant la première option en tête dans le cas où des données insoupsonnées auraient été modifiées.
Pour les tests, j'ai sauvegardé le dossier des données de tests pour ne pas avoir à refaire la réplication à chaque fois.

2020-04-18 11:47 UTC, garnier5 commented
Finalement, il y a beaucoup trop de données.
Je vais essayer de relancer la réplication...

2020-04-18 12:33 UTC, garnier5 commented
Avec des données fraichement répliquées, je vous confirme que tous les tests de la v2 fonctionnent (lorsque l'on ajoute steatite).

2020-04-18 12:56 UTC, benel approved these changes

2020-04-18 12:57 UTC, merged