REFACTORING : Filter for streamed long polling solution (Hypertopic/Porphyry#52)
Hypertopic/Argos pull request #59
Opened 2020-05-23 13:04 UTC by garnier5

Le filtre permettant de créer un eventsource dans la page des items.

2020-05-26 08:16 UTC, benel commented on app/filters/item.js
> +  return false;
You could rewrite the whole function implementation as : 
```js
return doc.item_corpus === req.query.corpus;
```

2020-06-12 16:30 UTC, garnier5 commented
Le filtre est mis à jour, et le `rewrite` a été ajouté.

2020-06-16 09:07 UTC, benel requested changes
Merci @garnier5. Une dernière petite modification...

2020-06-16 09:07 UTC, benel commented on app/rewrites.json
> +    "query": {
Vous pourriez ajouter `"feed": "eventsource"`. Ça permettrait de simplifier l'appel dans Porphyry (d'autant plus que ce serait logique vu le nom de la ressource que ce que l'on récupère soit justement des _events_).

2020-06-16 09:07 UTC, benel commented on app/rewrites.json
> +      "filter": "argos/item"
Le nom du filtre n'est pas formidable maintenant qu'il gère aussi les points de vue...
Pourquoi pas "events" ?

2020-06-16 09:07 UTC, benel commented on app/filters/item.js
> +  return ((doc.item_corpus === req.query.corpus) || (doc.viewpoint_name && (req.query.viewpoint.indexOf(doc._id) > -1)));
Pour que l'expression soit symétrique peut-être ajouter `doc.item_corpus &&` devant le premier terme.

Car il est vrai que si `req.query.corpus` est `undefined`, je crains que le filtre ne filtre plus rien du tout...

2020-06-16 16:15 UTC, benel commented
Merged as 0917f6b214155837612284c8c6f1021181ed7a5d (commit title was edited).

Deployed in Argos 4.4.0.

2020-06-16 16:15 UTC, closed without merging